## https://github.com/mpeterv/hererocks
language: python # Need python environment for pip
sudo: false # Use container-based infrastructure

env:
  - LUA="lua 5.1"
  - LUA="lua 5.2"
  - LUA="lua 5.3"
  - LUA="luajit 2.0"
  - LUA="luajit 2.1"

before_install:
  - pip install hererocks
  - hererocks here -r^ --$LUA # Install latest LuaRocks version
                              # plus the Lua version for this build job
                              # into 'here' subdirectory
  - export PATH=$PATH:$PWD/here/bin # Add directory with all installed binaries to PATH

install:
  - luarocks install busted # Install https://github.com/Olivine-Labs/busted

script:
  - busted specs # Run the specs

after_success:
  - .travis/push.sh

notifications:
  email:
    on_success: change
    on_failure: always
